# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "bcache" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda";
  networking.hostName = "hetzner";

  /*boot.kernelPackages = lib.mkForce (pkgs.linuxPackagesFor (pkgs.linux_testing_bcachefs.override ({
                date = "2022-03-21";
                commit = "c38b7167aa5f3b1b91dcc93ade57f30e95064590";
                diffHash = "sha256-qWNXf+8UhJhw+g3AiHENZaHtwwJhp0JILCDq2mFmOxQ=";
            })));*/

  fileSystems."/" =
    { device = "/dev/disk/by-id/ata-ST2000NM0033-9ZM175_Z1X0GVYB-part2:/dev/disk/by-id/ata-ST2000NM0033-9ZM175_Z1X0GVAA-part2";
      fsType = "bcachefs";
      options = [ "compression=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/ata-ST2000NM0033-9ZM175_Z1X0GVYB-part1";
      fsType = "ext4";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.overlays = [
    (self: super:
      {
        bcachefs-tools = super.bcachefs-tools.overrideAttrs ({...}: {
            src = pkgs.fetchFromGitHub {
                owner = "koverstreet";
                repo = "bcachefs-tools";
                rev = "f3cdace86c8b60a4efaced23b2d31c16dc610da9";
                sha256 = "sha256-KfTaBY2FE5xT/03czwu+Uwc+kqYy1FpHryB7orNk5ME=";
            };
        });
      })
  ];

  # not sure what exactly is needed for igpu encoding
  # https://nixos.wiki/wiki/Accelerated_Video_Playback
  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # LIBVA_DRIVER_NAME=iHD
      vaapiIntel         # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

  services.xserver = {
    enable = true;
  };
}
